// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjNEUb1r3wSX5_V9icVa3AikC8zADna8I',
    appId: '1:215460483742:web:6563447b909eddb198618f',
    messagingSenderId: '215460483742',
    projectId: 'jajananku-218a5',
    authDomain: 'jajananku-218a5.firebaseapp.com',
    storageBucket: 'jajananku-218a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgzeIJAPbtK7AWIi0U3xGSPif7MbFhV10',
    appId: '1:215460483742:android:98875dc0b47f174798618f',
    messagingSenderId: '215460483742',
    projectId: 'jajananku-218a5',
    storageBucket: 'jajananku-218a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ttZLqskUR6METWWug62D3arg3Eaocgo',
    appId: '1:215460483742:ios:33b76d48a1b45a5198618f',
    messagingSenderId: '215460483742',
    projectId: 'jajananku-218a5',
    storageBucket: 'jajananku-218a5.appspot.com',
    iosBundleId: 'com.example.jajananku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ttZLqskUR6METWWug62D3arg3Eaocgo',
    appId: '1:215460483742:ios:33b76d48a1b45a5198618f',
    messagingSenderId: '215460483742',
    projectId: 'jajananku-218a5',
    storageBucket: 'jajananku-218a5.appspot.com',
    iosBundleId: 'com.example.jajananku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjNEUb1r3wSX5_V9icVa3AikC8zADna8I',
    appId: '1:215460483742:web:58886bb2b42b544b98618f',
    messagingSenderId: '215460483742',
    projectId: 'jajananku-218a5',
    authDomain: 'jajananku-218a5.firebaseapp.com',
    storageBucket: 'jajananku-218a5.appspot.com',
  );
}
